customers = "data/customers.csv"
items = "data/order_items.csv"
orders = "data/orders.csv"
returns = "data/returns.csv"
data_output = "data/output/enriched_orders.parquet"
return_rates = "data/output/return_rates.csv"
top_refunds = "data/output/top_refunds.csv"
